#!/bin/bash
read -p "Do you want to install the dependencies (with apt)? [yY/nN] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	echo "running ./install-apt"
	./install-apt
	echo
fi

echo "running ./put"
./put

# vim:ft=sh
